server:
  port: 9900

logging:
  config: classpath:logback.xml
  level:
    root: info
    cn.sxgan.mapper: debug
spring:
  application:
    name: user-server

dubbo:

  scan:
    base-packages: cn.sxgan.cloud.service
  registry:
    address: zookeeper://192.168.0.200:2181
  protocol:
    name: dubbo
    port: 12222
  # 暂时关闭，以免端口冲突
  application:
    qos-enable: false
  metadata-report:
    address: zookeeper://192.168.0.200:2181